#pragma once

#define ICON_MIN_FA 0xe005
#define ICON_MAX_FA 0xf8ff

#define ICON_FA_FILE_LINES "\xef\x85\x9c"
#define ICON_FA_TRASH "\xef\x87\xad"
#define ICON_FA_XMARK "\xef\x80\x8d"
#define ICON_FA_GEAR "\xef\x80\x93"
#define ICON_FA_CHEVRON_RIGHT "\xef\x81\x94"
#define ICON_FA_CHEVRON_LEFT "\xef\x81\x93"
#define ICON_FA_CHEVRON_DOWN "\xef\x81\xb8"
#define ICON_FA_BARS "\xef\x83\x89"
#define ICON_FA_HOUSE "\xef\x80\x95"
#define ICON_FA_BROOM "\xef\x94\x9a"
#define ICON_FA_FILE_ZIPPER "\xef\x87\x86"
#define ICON_FA_FILE_ARCHIVE "\xef\x87\x86"
#define ICON_FA_PAINTBRUSH "\xef\x87\xbc"
#define ICON_FA_EYE "\xef\x81\xae"
#define ICON_FA_EYE_SLASH "\xef\x81\xb0"
#define ICON_FA_RIGHT_TO_BRACKET "\xef\x82\x90"
#define ICON_FA_RIGHT_FROM_BRACKET "\xef\x82\x8b"
#define ICON_FA_ROTATE "\xef\x80\xa1"
#define ICON_FA_WINDOW_MAXIMIZE "\xef\x89\x8e"
#define ICON_FA_WINDOW_MINIMIZE "\xef\x89\x91"
#define ICON_FA_WINDOW_RESTORE "\xef\x89\x92"
#define ICON_FA_INFO "\xef\x84\xa9"
#define ICON_FA_CIRCLE_INFO "\xef\x81\x9a"
#define ICON_FA_BELL "\xef\x83\xb3"
#define ICON_FA_DOWNLOAD "\xef\x80\x99"
#define ICON_FA_CHECK "\xef\x80\x8c"
#define ICON_FA_SLIDER "\xef\x80\xb2"
